//
//  AvailablePrograms.swift
//  CampusConnect
//
//  Created by Timothy Catibog on 2019-11-19.
//  Copyright © 2019 PROG31975. All rights reserved.
//

import Foundation

/**
    List of all the available programs at Sheridan.
    - Author: Timothy Catibog
*/
class AvailablePrograms : NSObject {
    let programs : [String] = [
        "Accounting, Business Administration",
        "Accounting, Honours Bachelor of Business Administration",
        "Advanced Manufacturing Management",
        "Advanced Special Effects Makeup, Prosthetics and Props",
        "Advanced Television and Film",
        "Advertising and Marketing Communications - Management",
        "Advertising - Account Management",
        "Animal Care",
        "Animation, Honours Bachelor of",
        "Apprenticeship Training Programs",
        "Architectural Technician/Technology",
        "Art Fundamentals",
        "Art and Art History (Honours Bachelor of Arts)",
        "Athletic Therapy, Honours Bachelor of Applied Health Sciences",
        "Bachelor of Computing and Network Communications (Honours) - Internet Communications Technology",
        "Business",
        "Business Analysis and Process Management",
        "Ceramics, Honours Bachelor of Craft and Design",
        "Chemical Engineering Technology",
        "Chemical Engineering Technology - Environmental",
        "Chemical Laboratory Technician",
        "Child and Youth Care",
        "Communication, Culture, Information & Technology",
        "Community Safety, Honours Bachelor of",
        "Community and Justice Services",
        "Computer Animation",
        "Computer Engineering Technician/Technology",
        "Computer Programmer",
        "Computer Systems Technician - Software Engineering",
        "Computer Systems Technology - Software Development and Network Engineering",
        "Computer Systems Technology - Systems Analyst",
        "Creative Industries Management",
        "Creative Writing and Publishing, Honours Bachelor of",
        "Digital Creature Animation - Technical Direction",
        "Digital Product Design",
        "Early Childhood Education",
        "Early Childhood Education - Intensive",
        "Early Childhood Leadership, Honours Bachelor of",
        "Educational Support",
        "Educational Support - Fast Track Intensive",
        "Electrical Engineering Technician",
        "Electrical Engineering, Bachelor of Engineering",
        "Electrical Techniques",
        "Electromechanical Engineering Technician/Technology",
        "Electronics Engineering Technician/Technology",
        "English Language Studies (ESL)",
        "Environmental Control",
        "Environmental Technician",
        "Film and Television, Honours Bachelor of",
        "Finance, Business Administration",
        "Finance, Honours Bachelor of Business Administration",
        "Furniture, Honours Bachelor of Craft and Design",
        "Game Design, Honours Bachelor of",
        "Game Development - Advanced Programming",
        "Game Level Design",
        "General Arts and Science - University Profile",
        "Glass, Honours Bachelor of Craft and Design",
        "Human Resources Management",
        "Human Resources Management, Honours Bachelor of Business Administration",
        "Human Resources, Business Administration",
        "Illustration, Honours Bachelor of",
        "Industrial Design, Honours Bachelor of Craft and Design",
        "Information Systems Security, Honours Bachelor of Applied Information Sciences",
        "Information Technologies Support Services",
        "Interaction Design, Honours Bachelor of",
        "Interactive Media Management",
        "Interior Decorating",
        "Interior Design, Honours Bachelor of",
        "International Business Management",
        "Internet Communications Technology",
        "Investigation - Public and Private",
        "Journalism",
        "Journalism - New Media",
        "Kinesiology and Health Promotion, Honours Bachelor of Health Sciences",
        "Makeup for Media and Creative Arts",
        "Marketing Management",
        "Marketing Management, Honours Bachelor of Business Administration",
        "Marketing, Business Administration",
        "Mechanical Engineering Technician/Technology",
        "Mechanical Engineering Technician/Technology - Design & Drafting",
        "Mechanical Engineering, Bachelor of Engineering",
        "Media Fundamentals",
        "Mobile Computing, Honours Bachelor of Computer Science",
        "Music Scoring for Screen and Stage",
        "Music Theatre Performance, Honours Bachelor of",
        "Office Administration - Executive",
        "Office Administration - Health Services",
        "Office Administration - Legal",
        "Paralegal",
        "Performing Arts - Preparation",
        "Personal Support Worker",
        "Pharmacy Technician",
        "Photography, Honours Bachelor of",
        "Plumbing Technician",
        "Plumbing, Mechanical Techniques",
        "Police Foundations",
        "Practical Nursing",
        "Pre-Health Sciences Pathway to Advanced Diplomas and Degrees",
        "Professional Accounting",
        "Project Management",
        "Public Relations - Corporate Communications",
        "Quality Assurance - Manufacturing and Management",
        "Social Service Worker",
        "Social Service Worker - Gerontology",
        "Supply Chain Management, Honours Bachelor of Business Administration",
        "Teaching English to Speakers of Other Languages (TESOL Plus)",
        "Technical Production for the Performing Arts Industry",
        "Technology Fundamentals",
        "Textiles, Honours Bachelor of Craft and Design",
        "Theatre and Drama Studies (Honours Bachelor of Arts)",
        "Tool Making, Mechanical Technician",
        "Tool and Die Maker, Mechanical Techniques",
        "Veterinary Technician",
        "Visual Effects",
        "Visual Merchandising Arts",
        "Visual and Creative Arts",
        "Welding and Fabrication Technician/Welding Techniques"
    ]
}
